services:
  korobas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${KOROBAS_BASE_IMAGE:-scottyhardy/docker-remote-desktop:latest}
        KOROBAS_UID: 1000
        KOROBAS_GID: 1000
        KOROBAS_IMAGE: ${KOROBAS_IMAGE:-ghcr.io/psauxwwf/korobas-desktop:latest}
    container_name: korobas
    hostname: korobas
    image: ${KOROBAS_IMAGE:-ghcr.io/psauxwwf/korobas-desktop:latest}
    init: true
    restart: unless-stopped
    environment:
      KOROBAS_AUTHORIZED_KEYS: ${KOROBAS_AUTHORIZED_KEYS:-}
      KOROBAS_BIND_ADDRESS: ${KOROBAS_BIND_ADDRESS:-172.19.100.2}
      KOROBAS_IMAGE: ${KOROBAS_IMAGE:-ghcr.io/psauxwwf/korobas-desktop:latest}
      KOROBAS_PASSWORD: korobas
      OPENCODE_CORS: ${OPENCODE_CORS:-http://127.0.0.1:8000,http://172.19.100.2:8000}
      OPENCODE_SERVER_USERNAME: ${OPENCODE_SERVER_USERNAME:-korobas}
      OPENCODE_SERVER_PASSWORD: ${OPENCODE_SERVER_PASSWORD:-korobas}
      OPENCODE_PROXY: ${OPENCODE_PROXY:-false}
    volumes:
      - ./korobas:/home/korobas:Z
    networks:
      korobas:
        ipv4_address: 172.19.100.2
    cap_add:
      - NET_ADMIN
    stop_grace_period: 10s

networks:
  korobas:
    driver: bridge
    name: korobas
    ipam:
      config:
        - subnet: 172.19.100.0/24
          gateway: 172.19.100.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: br-korobas
