version: "3"

env:
  COMPOSE_BAKE: true

tasks:
  build:
    desc: build desktop and core images
    cmds:
      - task: build:desktop
      - task: build:core

  push:
    desc: build and push images
    cmds:
      - task: build
      - docker push ghcr.io/psauxwwf/korobas-core:latest
      - docker push ghcr.io/psauxwwf/korobas-desktop:latest

  build:desktop:
    desc: build desktop image with xrdp
    env:
      KOROBAS_BASE_IMAGE: scottyhardy/docker-remote-desktop:latest
      KOROBAS_IMAGE: ghcr.io/psauxwwf/korobas-desktop:latest
    cmds:
      - docker compose build

  build:core:
    desc: build core image without xrdp
    env:
      KOROBAS_BASE_IMAGE: debian:13
      KOROBAS_IMAGE: ghcr.io/psauxwwf/korobas-core:latest
    cmds:
      - docker compose build

  up:
    desc: rebuild and up container
    cmds:
      - docker compose up --force-recreate --build

  release:
    desc: package and publish github release
    cmds:
      - rm -f korobas.tar.gz
      - tar -I 'pigz -9 -p$(nproc)' --exclude='korobas/.proxychains' --exclude='korobas/.local/share/opencode' --exclude='korobas/.env' --exclude='korobas/.cache' --exclude='korobas/.bash_history' -cf korobas.tar.gz docker-compose.yaml korobas
      - |
        TAG=$(date +v%m.%d.%H)
        gh release create "$TAG" korobas.tar.gz
